led:led.c
	gcc -Wall led.c -o led -lwiringPi
	gcc -Wall LED.c -o LED -lwiringPi
	gcc -Wall pcf8574.c -o pcf8574 -lwiringPi
	gcc -Wall PCF8574.c -o PCF8574 -lwiringPi
clean:
	rm led LED pcf8574 PCF8574

